/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Address {
  'country' : string,
  'city' : string,
  'postalCode' : string,
  'stateOrProvince' : string,
  'addressLine2' : [] | [string],
  'phoneNumber' : string,
  'streetAddress' : string,
}
export interface Animal {
  'birthDate' : bigint,
  'passingDate' : [] | [bigint],
  'name' : string,
  'photo' : [] | [ExternalBlob],
}
export interface AstCloudOrder {
  'id' : bigint,
  'paymentStatus' : PaymentStatus,
  'contactInfo' : ContactInfo,
  'paymentMethod' : PaymentMethod,
  'owner' : Principal,
  'animal' : Animal,
  'headstoneDesign' : HeadstoneDesign,
  'shippingAddress' : Address,
  'buyerInfo' : BuyerInfo,
}
export interface BlobSlot {
  'key' : string,
  'blob' : ExternalBlob,
  'name' : string,
}
export interface BuyerInfo { 'lastName' : string, 'firstName' : string }
export interface ContactInfo { 'email' : string, 'phoneNumber' : string }
export type ExternalBlob = Uint8Array;
export interface HeadstoneDesign {
  'peninsulaFrame' : ExternalBlob,
  'squareFrame' : ExternalBlob,
  'ovalFrame' : ExternalBlob,
  'headstoneFrame' : ExternalBlob,
  'roundFrame' : ExternalBlob,
}
export type PaymentMethod = { 'stripe' : null } |
  { 'crypto' : null } |
  { 'paypal' : null };
export type PaymentStatus = { 'pending' : null } |
  { 'completed' : string } |
  { 'failed' : string };
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile { 'name' : string, 'email' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'getAllHeadstoneDesigns' : ActorMethod<[], Array<HeadstoneDesign>>,
  'getBlobByKey' : ActorMethod<[string], [] | [BlobSlot]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getOrders' : ActorMethod<[], Array<AstCloudOrder>>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'listBlobs' : ActorMethod<[], Array<BlobSlot>>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'submitOrder' : ActorMethod<
    [
      string,
      bigint,
      [] | [bigint],
      PaymentMethod,
      ExternalBlob,
      ExternalBlob,
      ExternalBlob,
      ExternalBlob,
      ExternalBlob,
      ExternalBlob,
      Address,
      BuyerInfo,
      ContactInfo,
    ],
    bigint
  >,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'uploadBlob' : ActorMethod<[string, ExternalBlob, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];